server:
  port: 8080

spring:
  application:
    name: wallet-server
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized


app:
  env: "default"
  rpc:
    eth:
      mainnet: "https://eth-mainnet.example"
      goerli: "https://goerli.example"
      dev: "http://127.0.0.1:8545"
    btc:
      mainnet: "https://blockstream.info/api"
      testnet: "https://blockstream.info/testnet/api"
  security:
    allowOrigins: "https://your-frontend.example"
