
server:
  port: 8080

app:
  env: "default"
  blockscout:
    eth:
      mainnet: "https://eth.blockscout.com/api/v2/addresses"
      sepolia: "https://eth-sepolia.blockscout.com/api/v2/addresses"
  rpc:
    eth:
      mainnet: "https://eth-mainnet.example"
      sepolia: "https://ethereum-sepolia-rpc.publicnode.com"
    btc:
      mainnet: "https://blockstream.info/api"
      testnet: "https://blockstream.info/testnet/api"
  security:
    allowOrigins: "*"

  auth:
    enabled: false # Authentication switch, disabled by default
    androidKey: "android-demo-key"
    iosKey: "ios-demo-key"
