server:
  port: 8080

spring:
  application:
    name: wallet-server
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

app:
  env: "default"
  rpc:
    ethUrl: "https://eth-mainnet.example"
    btcUrl: "https://blockstream.info/api"
  security:
    allowOrigins: "https://your-frontend.example"
